#!/usr/bin/env node
/**
 * Generate TypeScript types from FastAPI OpenAPI schema
 * 
 * This script fetches the OpenAPI schema from the FastAPI backend
 * and generates TypeScript types for use in the frontend.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const API_URL = process.env.API_URL || 'http://localhost:8000';
const OPENAPI_SCHEMA_URL = `${API_URL}/openapi.json`;
const OUTPUT_FILE = path.join(__dirname, '../lib/api-types.ts');

console.log('🔄 Generating TypeScript types from FastAPI schema...');
console.log(`   Fetching schema from: ${OPENAPI_SCHEMA_URL}`);

try {
  // Check if openapi-typescript is installed
  try {
    execSync('npx openapi-typescript --version', { stdio: 'ignore' });
  } catch (e) {
    console.error('❌ openapi-typescript not found. Installing...');
    execSync('npm install --save-dev openapi-typescript', { stdio: 'inherit' });
  }

  // Fetch OpenAPI schema and generate types
  console.log('   Generating types...');
  execSync(
    `npx openapi-typescript "${OPENAPI_SCHEMA_URL}" -o "${OUTPUT_FILE}"`,
    { stdio: 'inherit' }
  );

  // Add a header comment to the generated file
  const generatedContent = fs.readFileSync(OUTPUT_FILE, 'utf8');
  const header = `/**
 * Auto-generated TypeScript types from FastAPI OpenAPI schema
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by scripts/generate-types.js
 * Run 'npm run generate:types' to regenerate
 * 
 * Generated from: ${OPENAPI_SCHEMA_URL}
 * Generated at: ${new Date().toISOString()}
 */

`;
  
  fs.writeFileSync(OUTPUT_FILE, header + generatedContent);

  console.log('✅ Types generated successfully!');
  console.log(`   Output: ${OUTPUT_FILE}`);
} catch (error) {
  console.error('❌ Failed to generate types:', error.message);
  
  // If API is not running, create a fallback types file
  if (error.message.includes('ECONNREFUSED') || error.message.includes('fetch')) {
    console.log('⚠️  API server not running. Creating fallback types...');
    
    const fallbackTypes = `/**
 * Auto-generated TypeScript types from FastAPI OpenAPI schema
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by scripts/generate-types.js
 * 
 * NOTE: This is a fallback file. Run 'npm run generate:types' with the API server running
 * to generate complete types from the actual OpenAPI schema.
 */

// Fallback types - regenerate when API is available
export interface PerformanceResponse {
  performance: Array<{
    timestamp: string;
    queryCount: number;
    avgLatency: number;
    p95Latency: number;
    indexHits: number;
    indexMisses: number;
  }>;
  indexImpact: Array<{
    indexName: string;
    tableName: string;
    fieldName: string;
    improvement: number;
    queryCount: number;
    beforeCost: number;
    afterCost: number;
  }>;
  explainStats: {
    total_attempts: number;
    success_rate: number;
    cached_hit_rate: number;
    fast_explain_rate: number;
    analyze_explain_rate: number;
    successful: number;
    failed: number;
    cached_hits: number;
    fast_explain_used: number;
    analyze_explain_used: number;
  } | null;
}

export interface HealthResponse {
  indexes: Array<{
    indexName: string;
    tableName: string;
    bloatPercent: number;
    sizeMB: number;
    usageCount: number;
    lastUsed: string;
    healthStatus: 'healthy' | 'warning' | 'critical';
  }>;
  summary: {
    totalIndexes: number;
    healthyIndexes: number;
    warningIndexes: number;
    criticalIndexes: number;
    totalSizeMB: number;
    avgBloatPercent: number;
  };
}

export interface ExplainStats {
  total_attempts: number;
  success_rate: number;
  cached_hit_rate: number;
  fast_explain_rate: number;
  analyze_explain_rate: number;
  successful: number;
  failed: number;
  cached_hits: number;
  fast_explain_used: number;
  analyze_explain_used: number;
}
`;

    fs.writeFileSync(OUTPUT_FILE, fallbackTypes);
    console.log('✅ Fallback types created. Run API server and regenerate for complete types.');
  } else {
    process.exit(1);
  }
}

