export type UseCase = { slug: string; title: string; description: string; question: string; answer: string; command: string; evidence: string[] };

export const useCases: UseCase[] = [
  { slug: "should-i-add-this-postgres-index", title: "Should I add this PostgreSQL index?", description: "Check whether a proposed PostgreSQL index is supported by the queries your database actually runs before merging it.", question: "A migration adds an index, but which real queries need it?", answer: "IndexPilot matches the exact CREATE INDEX to aggregate pg_stat_statements workload, existing indexes, and optional HypoPG plans. It returns evidence for a benchmark decision without applying the migration.", command: "indexpilot review --migration-file migration.sql --hypopg", evidence: ["Observed query shapes and call counts", "Comparable existing indexes", "Optional hypothetical planner selection"] },
  { slug: "postgres-index-not-used", title: "Why might PostgreSQL ignore my proposed index?", description: "Test whether PostgreSQL selects a proposed index for representative query shapes before creating it.", question: "A proposed index looks useful, but PostgreSQL may still prefer a sequential scan.", answer: "IndexPilot can create a session-local HypoPG index and ask PostgreSQL whether representative workload shapes select it. It does not diagnose whether an existing production index is safe to keep or drop, and planner evidence is not a latency guarantee.", command: "indexpilot review --candidate-file proposed-index.sql --hypopg", evidence: ["Planner selected the exact hypothetical shape", "Estimated planner-cost change", "Inconclusive result when evidence is insufficient"] },
  { slug: "duplicate-postgres-index", title: "Does this migration add a duplicate PostgreSQL index?", description: "Find leading-prefix overlap between a proposed B-tree index and indexes already present in PostgreSQL.", question: "A new index can duplicate storage and write cost already paid for another index.", answer: "IndexPilot compares the proposed index shape with visible catalog indexes and reports existing_overlap for human review. It never drops either index automatically.", command: "indexpilot review --migration-file migration.sql --fail-on existing_overlap", evidence: ["Exact proposed column order", "Existing leading-prefix coverage", "Portable Markdown, JSON, and SARIF reports"] },
  { slug: "test-postgres-index-before-creating", title: "Test a PostgreSQL index before creating it", description: "Use HypoPG and real workload evidence to evaluate a proposed PostgreSQL index without creating physical DDL.", question: "Building an index just to see whether the planner might use it is slow and leaves cleanup work.", answer: "With HypoPG, IndexPilot evaluates the proposed shape inside a read-only review session. It does not execute the supplied CREATE INDEX or run EXPLAIN ANALYZE.", command: "indexpilot review --candidate-sql 'CREATE INDEX ON public.orders (tenant_id, created_at)' --hypopg", evidence: ["No physical index created", "No migration executed", "Positive verdict means benchmark next—not safe to ship"] },
  { slug: "postgres-index-review-in-ci", title: "Review PostgreSQL index migrations in CI", description: "Add a read-only evidence gate for CREATE INDEX migrations and retain review artifacts with each pull request.", question: "Code review can see the DDL, but it cannot see whether production-like workload supports it.", answer: "Run IndexPilot in CI against a representative PostgreSQL target. Gate only the verdicts your team chooses and retain the evidence for reviewers.", command: "indexpilot review --migration-file migration.sql --sarif-output indexpilot.sarif --fail-on existing_overlap", evidence: ["Opt-in exit-code gates", "SARIF for code scanning", "Read-only database path"] },
];

export function findUseCase(slug: string) { return useCases.find((item) => item.slug === slug); }
