"""Type stubs for sklearn.preprocessing."""

class StandardScaler:
    """Standard Scaler stub."""
    def __init__(self, **kwargs: object) -> None: ...
    def fit(self, X: object) -> "StandardScaler": ...
    def transform(self, X: object) -> object: ...
    def fit_transform(self, X: object) -> object: ...

class LabelEncoder:
    """Label Encoder stub."""
    def __init__(self) -> None: ...
    def fit(self, y: object) -> "LabelEncoder": ...
    def transform(self, y: object) -> object: ...
    def fit_transform(self, y: object) -> object: ...

