"""Type stubs for psycopg2.connection - Connection class"""

from typing import TypeVar

# Type variable for cursor factory
_T_cur = TypeVar("_T_cur")

class connection:
    """PostgreSQL database connection"""
    
    def cursor(self, cursor_factory: type[_T_cur] | None = None) -> _T_cur: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> "connection": ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object) -> None: ...

