"""Type stubs for psycopg2.extras - Extended functionality"""

# RealDictCursor returns dict-like rows
class RealDictCursor:
    """Cursor that returns rows as dictionaries"""

    def execute(self, query: str, vars: object = None) -> None: ...
    def fetchone(self) -> dict[str, object] | None: ...
    def fetchall(self) -> list[dict[str, object]]: ...
    def fetchmany(self, size: int = 1) -> list[dict[str, object]]: ...
    def close(self) -> None: ...
    @property
    def rowcount(self) -> int: ...

# RealDictRow is an alias for dict[str, object] in psycopg2
RealDictRow = dict[str, object]
