"""Type stubs for sklearn.ensemble."""

class RandomForestRegressor:
    """Random Forest Regressor stub."""
    def __init__(self, *, n_estimators: int = 100, **kwargs: object) -> None: ...
    def fit(self, X: object, y: object) -> RandomForestRegressor: ...
    def predict(self, X: object) -> object: ...
