/**
 * Auto-generated TypeScript types from FastAPI OpenAPI schema
 * 
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated by scripts/generate-types.js
 * Run 'npm run generate:types' to regenerate
 * 
 * Generated from: http://localhost:8000/openapi.json
 * Generated at: 2025-12-07T17:30:00.000Z
 * 
 * NOTE: This is a fallback file. Run 'npm run generate:types' with the API server running
 * to generate complete types from the actual OpenAPI schema.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              status: string;
              service: string;
            };
          };
        };
      };
    };
  };
  "/api/performance": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["PerformanceResponse"];
          };
        };
        500: {
          content: {
            "application/json": {
              detail: string;
            };
          };
        };
      };
    };
  };
  "/api/health": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["HealthResponse"];
          };
        };
        500: {
          content: {
            "application/json": {
              detail: string;
            };
          };
        };
      };
    };
  };
  "/api/explain-stats": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["ExplainStats"];
          };
        };
        500: {
          content: {
            "application/json": {
              detail: string;
            };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    PerformanceResponse: {
      performance: Array<{
        timestamp: string;
        queryCount: number;
        avgLatency: number;
        p95Latency: number;
        indexHits: number;
        indexMisses: number;
      }>;
      indexImpact: Array<{
        indexName: string;
        tableName: string;
        fieldName: string;
        improvement: number;
        queryCount: number;
        beforeCost: number;
        afterCost: number;
      }>;
      explainStats: components["schemas"]["ExplainStats"] | null;
    };
    HealthResponse: {
      indexes: Array<{
        indexName: string;
        tableName: string;
        bloatPercent: number;
        sizeMB: number;
        usageCount: number;
        lastUsed: string;
        healthStatus: "healthy" | "warning" | "critical";
      }>;
      summary: {
        totalIndexes: number;
        healthyIndexes: number;
        warningIndexes: number;
        criticalIndexes: number;
        totalSizeMB: number;
        avgBloatPercent: number;
      };
    };
    ExplainStats: {
      total_attempts: number;
      success_rate: number;
      cached_hit_rate: number;
      fast_explain_rate: number;
      analyze_explain_rate: number;
      successful: number;
      failed: number;
      cached_hits: number;
      fast_explain_used: number;
      analyze_explain_used: number;
    };
  };
}

export type { paths, components };

